name: Simple AI Vision
version: "1.4.7"
slug: simple_ai_vision
description: Lightweight AI camera snapshot analyzer using go2rtc and Telegram alerts
url: "https://github.com/minhhungtsbd/my_hass_addon_public/tree/main/simple_ai_vision"
arch:
  - amd64
  - aarch64
startup: application
boot: auto
init: false
host_network: false
ingress: true
ingress_port: 8000
homeassistant_api: true
panel_icon: mdi:cctv
webui: "http://[HOST]:[PORT:8000]/"
ports:
  8000/tcp: 8000
ports_description:
  8000/tcp: Simple AI Vision API
options: {}
schema: {}
